### ISSUE TITLE
Internal error while processing SQL query (PostgreSQL 9.4)

### ISSUE THREAD

**Issue by iAchilles** [processone/ejabberd#1152]
> What version of ejabberd are you using?
16.03

> What operating system (version) are you using?
Debian Jessie x64

> How did you install ejabberd (source, package, distribution)?
https://packages.debian.org/ru/jessie-backports/ejabberd

> What did not work as expected? Are there error messages in the log? 
2016-06-13 01:03:16.173 [error] <0.356.0>@ejabberd_odbc:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsql,prepare,[<0.379.0>,<<"Q56243172">>,[<<"select username, jid, nick, subscription, ask, askmessage, server, subscribe, type from rosterusers where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_odbc,sql_query_internal,1,[{file,"src/ejabberd_odbc.erl"},{line,515}]},{ejabberd_odbc,run_sql_cmd,4,[{file,"src/ejabberd_odbc.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
2016-06-13 01:03:16.173 [error] <0.465.0>@ejabberd_odbc:check_error:991 SQL query 'Q56243172' at {odbc_queries,304} failed: <<"internal error">>
2016-06-13 01:03:16.177 [error] <0.361.0>@ejabberd_odbc:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsql,prepare,[<0.384.0>,<<"Q11745357">>,[<<"select name from privacy_default_list where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_odbc,sql_query_internal,1,[{file,"src/ejabberd_odbc.erl"},{line,515}]},{ejabberd_odbc,run_sql_cmd,4,[{file,"src/ejabberd_odbc.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

**Comment by iAchilles** [comment]
I installed from source v16.04 but still get bunch of errors in logs:

>>2016-06-13 04:35:14.165 [error] <0.382.0>@ejabberd_sql:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsq
l,prepare,[<0.405.0>,<<"Q56243172">>,[<<"select username, jid, nick, subscription, ask, askmessage, server, subscribe, type from rosterusers where use
rname=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,515}]},{ejabberd_sql,
run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{fi
le,"proc_lib.erl"},{line,237}]}]}

>>2016-06-13 04:35:14.165 [error] <0.486.0>@ejabberd_sql:check_error:991 SQL query 'Q56243172' at {sql_queries,303} failed: <<"internal error">>
2016-06-13 04:35:14.216 [error] <0.379.0>@ejabberd_sql:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsq
l,prepare,[<0.402.0>,<<"Q11745357">>,[<<"select name from privacy_default_list where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejab
berd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,515}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,398}]},{p1_
fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

>>2016-06-13 04:35:14.216 [error] <0.486.0>@ejabberd_sql:check_error:991 SQL query 'Q11745357' at {sql_queries,489} failed: <<"internal error">>
2016-06-13 04:35:14.237 [error] <0.383.0>@ejabberd_sql:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsql,prepare,[<0.406.0>,<<"Q98606141">>,[<<"select vcard from vcard where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,515}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

>>2016-06-13 04:35:14.237 [error] <0.476.0>@ejabberd_sql:check_error:991 SQL query 'Q98606141' at {sql_queries,484} failed: <<"internal error">>

>>2016-06-13 04:35:14.238 [error] <0.377.0>@ejabberd_sql:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsql,prepare,[<0.400.0>,<<"Q11745357">>,[<<"select name from privacy_default_list where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,515}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

>>2016-06-13 04:35:14.238 [error] <0.375.0>@ejabberd_sql:sql_query_internal:541 Internal error while processing SQL query: {error,function_clause,[{pgsql,prepare,[<0.398.0>,<<"Q56243172">>,[<<"select username, jid, nick, subscription, ask, askmessage, server, subscribe, type from rosterusers where username=">>,<<"$1">>]],[{file,"src/pgsql.erl"},{line,73}]},{ejabberd_sql,sql_query_internal,1,[{file,"src/ejabberd_sql.erl"},{line,515}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,398}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

>>2016-06-13 04:35:14.238 [error] <0.486.0>@ejabberd_sql:check_error:991 SQL query 'Q11745357' at {sql_queries,489} failed: <<"internal error">>

>>2016-06-13 04:35:14.238 [error] <0.472.0>@ejabberd_sql:check_error:991 SQL query 'Q56243172' at {sql_queries,303} failed: <<"internal error">>

**Comment by iAchilles** [comment]
I fixed this issue by updating erlang-p1-pgsql.

**Comment by diguliu** [comment]
Hey @iAchilles!

I'm having the EXACT same problem. I'm on a Debian Jessie x64 and using ejabberd 16.03 from jessie-backports as well. As anyone might notice, ejabberd error messages are really not that helpful...

So, I tried updating erlang-p1-pgsql as you suggested but I still have the same problem. Maybe what solves the issue is the combination of the source ejabberd 16.04 with this update but before going into installing ejabberd from source (which I'd rather not do if I was able to) can you confirm to which version you updated erlang-p1-pgsql? I assumed you updated to 1.1.0-2~bpo8+1 which is the current version for it on jessie-backports.

Another thing I'd like to confirm is if this problem is happening to you only with some users. With some other users consulting the rosters just work, no problem.

**Comment by iAchilles** [comment]
Hello,
try to run the following:
sudo apt-get purge erlang-p1-pgsql
sudo apt-get -t jessie-backports install erlang-p1-pgsql

**Comment by diguliu** [comment]
Hey @iAchilles,

I did what you suggested and no change. Even after multiple ejabberd restarts.
Here are my ejabberd and erlang-p1-pgsql versions.
```
aptitude show ejabberd
Pacote: ejabberd                             
Estado: instalado
Automaticamente instalado: não
Versão: 16.03-1~bpo8+1
Prioridade: opcional
Seção: net
Mantenedor: Ejabberd Packaging Team <ejabberd@deb.at>
Arquitetura: i386
Tamanho Descompactado: 5.744 k
Depende de: adduser, openssl, ucf, debconf (>= 0.5) | debconf-2.0, init-system-helpers (>= 1.18~), erlang-base (>= 1:17) | erlang-abi-17.0, erlang-asn1 (>= 1:17.3-dfsg), erlang-base (>= 1:17.3-dfsg)
            | erlang-base-hipe (>= 1:17.3-dfsg), erlang-crypto (>= 1:17.3-dfsg), erlang-inets (>= 1:17.3-dfsg), erlang-mnesia (>= 1:17.3-dfsg), erlang-odbc (>= 1:17.3-dfsg), erlang-public-key (>=
            1:17.3-dfsg), erlang-ssl (>= 1:17.3-dfsg), erlang-syntax-tools (>= 1:17.3-dfsg), erlang-lager, erlang-p1-cache-tab (>= 1.0.2), erlang-p1-iconv (>= 1.0.0), erlang-p1-stringprep (>=
            1.0.3), erlang-p1-tls (>= 1.0.1), erlang-p1-utils (>= 1.0.3), erlang-p1-xml (>= 1.1.11), erlang-p1-yaml (>= 1.0.3), erlang-p1-zlib (>= 1.0.1), erlang-xmerl
Sugere: apparmor, apparmor-utils, libunix-syslog-perl, imagemagick | graphicsmagick-imagemagick-compat, ejabberd-contrib (> 0.2015.08), erlang-luerl, erlang-oauth2, erlang-p1-mysql (>= 1.0.1),
        erlang-p1-pam (>= 1.0.0), erlang-p1-pgsql (>= 1.1.0), erlang-p1-sip (>= 1.0.2), erlang-p1-stun (>= 1.0.1), erlang-sqlite3, erlang-redis-client

# aptitude show erlang-p1-pgsql
Pacote: erlang-p1-pgsql                      
Novo: sim
Estado: instalado
Automaticamente instalado: não
Versão: 1.1.0-2~bpo8+1
Prioridade: opcional
Seção: libs
Mantenedor: Philipp Huebner <debalance@debian.org>
Arquitetura: i386
Tamanho Descompactado: 67,6 k
Depende de: erlang-base | erlang-abi-17.0, erlang-base (>= 1:17.3-dfsg) | erlang-base-hipe (>= 1:17.3-dfsg)
```

Error message (the same as yours) I get when running `ejabberdctl get_roster <user> <vhost>` for some specific users:
```
2016-07-06 14:07:25.741 [error] <0.557.0> ODBC: received unexpected info: {tcp_closed,#Port<0.12589>}

2016-07-06 14:07:25.742 [error] <0.557.0> gen_server <0.557.0> terminated with reason: {port_exit,memory_allocation_failed}
2016-07-06 14:07:25.742 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 0 neighbours exited with reason: {port_exit,memory_allocation_failed} in gen_server:terminate/6 line 737
2016-07-06 14:07:25.742 [error] <0.529.0>@ejabberd_odbc:check_error:991 SQL query 'Q56243172' at {odbc_queries,304} failed: connection_closed
2016-07-06 14:07:25.742 [error] <0.363.0> Supervisor odbc_sup had child [] started with {odbc,start_link_sup,undefined} at <0.557.0> exit with reason {port_exit,memory_allocation_failed} in context child_terminated
```

I'm really afraid the solution might be on ejabberd 16.04 together with erlang-p1-pgsql 1.1.0-2.

**Comment by diguliu** [comment]
My joruney continues. Debian backports updated ejabberd version to 16.06-2~bpo8+1 and erlang-p1-pgsql stayed 1.1.0-2~bpo8+1. I updated ejabberd to this version and still the problem continues. Buy now I have some news.

After exhausting manual brute force testing I discovered that the problem is the username size. I was really reluctant to believe it but after seeing the pattern where every user with big usernames were having the problem and the ones with smaller usernames were working I had to test it through.

So I went from the user I knew was breaking that had a username of length 13 to the user which I knew it was working that had a username of length 7. From 13 to 9 every user i tried had the same crash. When I got to 8 every user worked. The final test was fetching the roster with the username 'xxxxxxxx' (8 chars) and username 'xxxxxxxxx' (9 chars). As you would imagine, for some obscure reason, usernames with lenght > 8 crashes the query.

Now the question is: how do I solve this freaking problem?
