### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by LeoYReyes** [processone/ejabberd#1470]
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Windows 7 Enterprise and Windows Server 2012 R2 Standard

> How did you install ejabberd (source, package, distribution)?

Windows installer

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to cluster 2 ejabberd nodes. When I join 1 node to another, it looks like it is successful, but it looks like the 2 nodes in the cluster aren't in sync.

Steps I took to set the clustering:
1. Install ejabberd on server1 with the clustering option
2. Install ejabberd on server2 with the clustering option
3. Add the following entries in the hosts file (Windows/System32/drivers/etc/hosts) on both servers
   111.222.333.444 server1
   555.666.777.888 server2
4. Delete the mnesia directory under %APPDATA%/ejabberd/database/ on both servers
5. Make the following modifications to ejabberdctl.cfg
5.1. Uncomment and modify entry ERLANG_NODE=ejabberd@server1
5.2 Uncomment and modify entry INET_DIST_INTERFACE=111.222.333.444
5.3 Do the same for server2
6. Copy ejabberd config (ejabberd.yml) from server1 to server2
7. Start ejabberd on server1 with command: "ejabberdctl.cmd --node ejabberd@server1 start"
8. Copy cookie file from server1 to server2
9. Start ejabberd on server2 with command: "ejabberdctl.cmd --node ejabberd@server2 start"
10. Join server2 to server1 with command: "ejabberdctl.cmd --node ejabberd@server2 join_cluster 'ejabberd@server1'"
11. On server2 execute command: "ejabberdctl.cmd --node ejabberd@server2 list_cluster" with the following results:
      ejabberd@server1
      ejabberd@server2
12. On server1 execute command: "ejabberdctl.cmd --node ejabberd@server1 list_cluster" and get the following error:
![image](https://cloud.githubusercontent.com/assets/4027885/22026018/2204bef2-dc95-11e6-9abe-0c391f0377d9.png)

13. Restart ejabberd on server1 and then list_cluster lists both servers.
14. On server1 go into debug and executed mnesia:info() with the following results:
route          : with 7        records occupying 460      words of mem
ejabberd_commands: with 125      records occupying 30677    words of mem
sql_pool       : with 10       records occupying 442      words of mem
shaper         : with 2        records occupying 324      words of mem
local_config   : with 22       records occupying 1103     words of mem
acl            : with 4        records occupying 398      words of mem
access         : with 30       records occupying 912      words of mem
carboncopy     : with 0        records occupying 302      words of mem
pubsub_index   : with 0        records occupying 302      words of mem
http_bind      : with 0        records occupying 302      words of mem
reg_users_counter: with 1        records occupying 316      words of mem
schema         : with 20       records occupying 2876     words of mem
pubsub_last_item: with 0        records occupying 302      words of mem
oauth_token    : with 0        records occupying 302      words of mem
iq_response    : with 0        records occupying 302      words of mem
passwd         : with 0        records occupying 302      words of mem
temporarily_blocked: with 0        records occupying 302      words of mem
s2s            : with 0        records occupying 302      words of mem
muc_online_room: with 2        records occupying 341      words of mem
route_multicast: with 0        records occupying 302      words of mem
===> System info in version "4.13.3", debug level = none <===
opt_disc. Directory "c:/Users/lyreyes1/AppData/Roaming/ejabberd/database/mnesia" is used.
use fallback at restart = false
running db nodes   = [ejabberd@server2,ejabberd@server1]
stopped db nodes   = [] 
master node tables = []
remote             = []
ram_copies         = [access,acl,carboncopy,ejabberd_commands,http_bind,
                      iq_response,local_config,muc_online_room,
                      pubsub_last_item,reg_users_counter,route,
                      route_multicast,s2s,shaper,sql_pool,temporarily_blocked]
disc_copies        = [oauth_token,passwd,pubsub_index,schema]
disc_only_copies   = []
[{ejabberd@server2,disc_copies},{ejabberd@server1,disc_copies}] = [passwd,
                                                                      oauth_token,
                                                                      schema,
                                                                      pubsub_index]
[{ejabberd@server2,ram_copies},{ejabberd@server1,ram_copies}] = [route_multicast,
                                                                    muc_online_room,
                                                                    s2s,
                                                                    temporarily_blocked,
                                                                    iq_response,
                                                                    pubsub_last_item,
                                                                    reg_users_counter,
                                                                    http_bind,
                                                                    carboncopy,
                                                                    route]
[{ejabberd@server1,ram_copies}] = [shaper,local_config,acl,access,sql_pool,
                                    ejabberd_commands]
62 transactions committed, 35 aborted, 0 restarted, 8 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
ok

That is currently the setup i'm running.
It's also configured to use MSSQL as the database for archiving, MUC, and session manager.

How can I truly test that the 2 nodes are clustered properly?

I'm currently using ConverseJs as a client, and whenever I create a MUC(temporary) on one server, I am not able to properly connect to it on the other. 

Can someone tell me if the way I setup the cluster looks correct? If so then it might be something with the client. Is there a good method for testing the cluster?

**Comment by LeoYReyes** [comment]
So the issue that I am having seems to be caused by using SQL as the db for the session manager. I am now using mnesia as the db for the session manager and I am able to communicate between users on different nodes. So I am able to get it up and running for now, but maybe it would be good to take a look at what is going on when using SQL as the db for the session manager.

**Comment by jadijadi** [comment]
I'm having the same problem. when using the mysql for session manager, users on server 1 can not communicate with users on server2. the `sm` table on each server contains only users on that specific server & if i configure both nodes to use a single mysql db, each the 'PID' of each session is set as 0.A.0 and the next one 0.B.0. so the route module will try to route the users on the other server to 0.B.0 instead of xyz.B.0. 

any ideas on what should be done?

**Comment by zinid** [comment]
Ha, this is a bug and should be fixed

**Comment by tianxu0836** [comment]
Can anyone tell me how to setup cluster exactly
Why I never find a good document that describes how to configure cluster???

**Comment by LeoYReyes** [comment]
@tianxu0836 there is documentation at [https://docs.ejabberd.im/admin/guide/clustering/](https://docs.ejabberd.im/admin/guide/clustering/) 
If that isn't enough, try following the steps I took to setup the cluster, because mine is working using the steps I took.

**Comment by tianxu0836** [comment]
@LeoYReyes That document is too simple and doesn't have enough info.
I'm following your steps but still have a problem.
It shows "protocol 'inet_tcp':register/listen error: eaddrnotavil" after I tried to join cluster

After you "Install ejabberd on server1 with the clustering option" do you need to rename the node?
I noticed that after I installed ejabberd with clustering option, even though I assigned a node name to it, it still using ejabberd@localhost in the web portal.

Do you need to change any firewall settings?

**Comment by tianxu0836** [comment]
For cluster node name, should I use IP address or just the computer name?

**Comment by zinid** [comment]
@tianxu0836 node name looks like an email address, where domain part (after `@`) should be your hostname, yes.

**Comment by tianxu0836** [comment]
@zinid I don't have a DNS, so I'm using IP address for ejabberd server domain. Do you mean for the cluster node name I should also use ejabberd@xxx.xxx.xxx.xxx?

**Comment by zinid** [comment]
Well, yes, you can use IP address, but if you change it you have to perform "hostname migration" in ejabberd, which is not very comfortable operation.

**Comment by tianxu0836** [comment]
@zinid Right now I'm just testing clusters, but if I set up two clusters nodes on two different virtual machines with static IP addresses, can I use just use IP address for both of their ejabberd server domains and cluster node names?

**Comment by zinid** [comment]
Yes

**Comment by tianxu0836** [comment]
@zinid In that case, if I use ip address for everything. Can I still simply copy server1's ejabberd.yml to server2?

**Comment by zinid** [comment]
Yes, as long as you don't require any particular IP address somewhere, in `listen` section for example.

**Comment by tianxu0836** [comment]
@zinid Do you know why even though I assign IP address to node name like "ejabberd@xxx.xxx.xxx.xxx" in the setup wizard.
Is it still showing ejabberd@localhost in the web admin portal and in the database?
Do I need to rename the node manually or what?

This is what I got
![ssss2017-08-29_1421](https://user-images.githubusercontent.com/2152278/29844954-f059831a-8cc5-11e7-8ad8-d1ceda822ece.png)

**Comment by tianxu0836** [comment]
@zinid I got the error report like this

I keep getting this kind of error forever and no matter what I do.
I thought the setup wizard can take care of it, but it seems that does do anything?

[critical] <0.173.0>@ejabberd_mnesia:init:74 Node name mismatch: I'm [ejabberd@xxx.xxx.xxx.xxx], the database is owned by [ejabberd@localhost]
[critical] <0.173.0>@ejabberd_mnesia:init:76 Either set ERLANG_NODE in ejabberdctl.cfg or change node name in Mnesia

**Comment by LeoYReyes** [comment]
did you set the ERLAND_NODE=ejabberd@xxx.xxx.xxx.xxx in the ejabberdctl.cfg? You may also want to delete the mnesia database in %APPDATA%\ejabberd\database, and when you start up ejabberd again, it should recreate your database as whatever node you have set in the ejabberdctl.cfg.

**Comment by tianxu0836** [comment]
@LeoYReyes I did that in ejabberdctl.cfg. I also removed the database. it shows "protocol 'inet_tcp':register/listen error: eaddrnotavil" after I tried to join cluster

**Comment by LeoYReyes** [comment]
what are your INET_DIST_INTERFACE and ERL_EPMD_ADDRESS set to? Are those set to 127.0.0.1?

**Comment by tianxu0836** [comment]
@LeoYReyes I was using the default one, didn't change since I'm using IP address, I thought I don't need to change those. Should I change those to IP address too?

**Comment by tianxu0836** [comment]
@LeoYReyes Even though I delete db, it still creates db for ejabberd@localhost.
No matter what I do in the cfg file.
