### ISSUE TITLE
No PubSub with User Avatars (XEP-0084) possible

### ISSUE THREAD

**Issue by keyser-soeze** [processone/ejabberd#1669]
Hi guys,

Im using ejabberd 17.03 as an XMPP server for implementing [Cryptocat](https://github.com/cryptocat/cryptocat). Cryptocat uses the [stanza.io](https://github.com/legastero/stanza.io) library. Sending encrypted messages, the device manager and the OMEMO stuff works. Unfortunately the only thing that is not working is showing the avatars. Setting the avatar at startup works. But the avatar are not published/subscribed by the users. I activated the ejabberd-mod (mod_pubsub) for creating nodes (OMEMO uses these pattern, too) tried all plugins (pep plugin is of course activated). Every startup needs to set the avatar again. I already checked the XEPs (PubSub: XEP-0060, User Avatar: XEP-0084 and XEP-0163: Personal Eventing Protocol) and tried different ejabberd versions, but no success. Here you see an excerpt from the ejabberd logs for debugging purposes. Is it a ejabberd, Cryptocat or stanza.io issue?

Thanks for your help.

```
07:35:03.036 [debug] route:
#iq{id = <<"8188d7c9-ffb2-4b19-8038-130cc98f8d31">>,type = error,
    lang = <<"en">>,
    from = 
        {jid,<<"xxx">>,<<"localhost">>,<<>>,<<"xxx">>,<<"localhost">>,
            <<>>},
    to = 
        {jid,<<"xxx">>,<<"localhost">>,
            <<"135341455680197269271491802469322946">>,<<"xxx">>,
            <<"localhost">>,<<"135341455680197269271491802469322946">>},
    sub_els = 
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,<<"urn:xmpp:avatar:data">>,
                 [{ps_item,<<>>,<<"04">>,[],<<>>,<<>>}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined,undefined},
         #stanza_error{
             type = modify,code = 400,by = <<>>,reason = 'bad-request',
             text = undefined,
             sub_els = [{ps_error,'payload-required',undefined}]}],
    meta = #{ip => {172,17,0,1}}}

07:35:03.036 [debug] local route:
#iq{id = <<"8188d7c9-ffb2-4b19-8038-130cc98f8d31">>,type = error,
    lang = <<"en">>,
    from = 
        {jid,<<"xxx">>,<<"localhost">>,<<>>,<<"xxx">>,<<"localhost">>,
            <<>>},
    to = 
        {jid,<<"xxx">>,<<"localhost">>,
            <<"135341455680197269271491802469322946">>,<<"xxx">>,
            <<"localhost">>,<<"135341455680197269271491802469322946">>},
    sub_els = 
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,<<"urn:xmpp:avatar:data">>,
                 [{ps_item,<<>>,<<"04">>,[],<<>>,<<>>}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined,undefined},
         #stanza_error{
             type = modify,code = 400,by = <<>>,reason = 'bad-request',
             text = undefined,
             sub_els = [{ps_error,'payload-required',undefined}]}],
    meta = #{ip => {172,17,0,1}}}

07:35:03.036 [debug] processing packet to full JID:
#iq{id = <<"8188d7c9-ffb2-4b19-8038-130cc98f8d31">>,type = error,
    lang = <<"en">>,
    from = 
        {jid,<<"xxx">>,<<"localhost">>,<<>>,<<"xxx">>,<<"localhost">>,
            <<>>},
    to = 
        {jid,<<"xxx">>,<<"localhost">>,
            <<"135341455680197269271491802469322946">>,<<"xxx">>,
            <<"localhost">>,<<"135341455680197269271491802469322946">>},
    sub_els = 
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,<<"urn:xmpp:avatar:data">>,
                 [{ps_item,<<>>,<<"04">>,[],<<>>,<<>>}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined,undefined},
         #stanza_error{
             type = modify,code = 400,by = <<>>,reason = 'bad-request',
             text = undefined,
             sub_els = [{ps_error,'payload-required',undefined}]}],
    meta = #{ip => {172,17,0,1}}}

07:35:03.037 [debug] sending to process <0.511.0>:
#iq{id = <<"8188d7c9-ffb2-4b19-8038-130cc98f8d31">>,type = error,
    lang = <<"en">>,
    from = 
        {jid,<<"xxx">>,<<"localhost">>,<<>>,<<"xxx">>,<<"localhost">>,
            <<>>},
    to = 
        {jid,<<"xxx">>,<<"localhost">>,
            <<"135341455680197269271491802469322946">>,<<"xxx">>,
            <<"localhost">>,<<"135341455680197269271491802469322946">>},
    sub_els = 
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,<<"urn:xmpp:avatar:data">>,
                 [{ps_item,<<>>,<<"04">>,[],<<>>,<<>>}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined,undefined},
         #stanza_error{
             type = modify,code = 400,by = <<>>,reason = 'bad-request',
             text = undefined,
             sub_els = [{ps_error,'payload-required',undefined}]}],
    meta = #{ip => {172,17,0,1}}}

```

**Comment by cromain** [comment]
there was a bug on PEP in 17.03 which has been fixed. Please test again when 17.04 is out.

**Comment by keyser-soeze** [comment]
Just tried out with 17.04, still the same error...

**Comment by cromain** [comment]
Investigating this a but, I could not produce PEP/PubSub issues. I did not tested OMEMO anyway.
This errors returned by ejabberd means your client tried to publish an item without payload to the PEP node.

You can produce same kind of result sending mood without payload like this
```
<iq type="set" id="aac6a">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="http://jabber.org/protocol/mood">
<item id="current">
</item>
</publish>
</pubsub>
</iq>
```

quickly looking at stanza.io i see no protection against empty data in publishAvatar function. So it looks like stanza.io run in this situation, with data not containing avatar payload.

**Comment by keyser-soeze** [comment]
Hi Christophe, thanks for investigating. Im using ejabberd 17.06 now. It is still not working. So, what do you suggest? Publishing OMEMO bundles is working. Even setting avatars is working. But publishing avatars on a specific node unfortunately is not working.

Im using pub_sub module with sql db type and flat and pep plugins. I even disabled the flat plugin and tried only with pep plugin. 

Im always getting following errors from the backend (ejabberd). FYI: 'xxx' represents the username (JID).
Do i really have to publish avatar metadata? Im using ```image/png``` files as avatars.

```
#iq{id = <<"e232008d-38af-4bea-88be-8a9f9163694e">>,type = error,
    lang = <<"en">>,
    from = 
        {jid,<<"xxx">>,<<"localhost">>,<<>>,<<"xxx">>,<<"localhost">>,
            <<>>},
    to = 
        {jid,<<"xxx">>,<<"localhost">>,
            <<"137256196191844865461498928334688532">>,<<"xxx">>,
            <<"localhost">>,<<"137256196191844865461498928334688532">>},
    sub_els = 
        [{pubsub,undefined,undefined,undefined,
             {ps_publish,<<"urn:xmpp:avatar:data">>,
                 [{ps_item,<<>>,<<"11">>,[],<<>>,<<>>}]},
             undefined,undefined,undefined,undefined,undefined,undefined,
             undefined,undefined,undefined,undefined,undefined,undefined},
         #stanza_error{
             type = modify,code = 400,by = <<>>,reason = 'bad-request',
             text = undefined,
             sub_els = [{ps_error,'payload-required',undefined}]}],
    meta = #{ip => {172,18,0,1}}}
```

```
19:06:03.011 [debug] Won't add stanza for xxx@localhost/137256196191844865461498928334688532 to CSI queue
19:06:03.011 [debug] Flushing packets of xxx@localhost from CSI queue of xxx@localhost/137256196191844865461498928334688532
```

mod_client_state is configured like this:

```
mod_client_state:
    queue_chat_states: true
    queue_pep: true
    queue_presence: true
```

Thanks in advance for your help :)

**Comment by keyser-soeze** [comment]
@cromain any progress so far?

**Comment by cromain** [comment]
what was node config for this ? server can return this if item has NO payloads but node is configured to persist items or deliver payload.
If payload is expected to be delivered, item MUST contain a payload.
