### ISSUE TITLE
ejabberdctl process_rosteritems - Stacktrace - problem

### ISSUE THREAD

**Issue by Snowmanko** [processone/ejabberd#2698]
Hi,
this command should delete all roster items in test.user@domain's user roster. Am I doing something wrong ? My goal is to delete whole roster of certain user. Please advice.

Thanks.

```
# ejabberdctl process_rosteritems delete any any test.user@domain *@*
There are 3016 roster items in total.
Problem 'error badarg' occurred executing the command.
Stacktrace: [{erlang,binary_to_list,[error],[]},
             {ejabberd_regexp,run,2,
                              [{file,"src/ejabberd_regexp.erl"},{line,40}]},
             {mod_admin_extra,is_regexp_match,2,
                              [{file,"src/mod_admin_extra.erl"},{line,1737}]},
             {mod_admin_extra,'-decide_rip_jid/2-fun-0-',3,
                              [{file,"src/mod_admin_extra.erl"},{line,1708}]},
             {lists,any,2,[{file,"lists.erl"},{line,1225}]},
             {mod_admin_extra,decide_rip,2,
                              [{file,"src/mod_admin_extra.erl"},{line,1693}]},
             {mod_admin_extra,rip,4,
                              [{file,"src/mod_admin_extra.erl"},{line,1653}]},
             {ejabberd_ctl,call_command,4,
                           [{file,"src/ejabberd_ctl.erl"},{line,352}]}]

```
I am using : 
```
erlang-asn1 1:19.2.1+dfsg-2+deb9u1
erlang-base 1:19.2.1+dfsg-2+deb9u1
erlang-crypto 1:19.2.1+dfsg-2+deb9u1
erlang-edoc 1:19.2.1+dfsg-2+deb9u1
erlang-eldap 1:19.2.1+dfsg-2+deb9u1
erlang-eunit 1:19.2.1+dfsg-2+deb9u1
erlang-goldrush 0.1.9-3bpo8+1
erlang-inets 1:19.2.1+dfsg-2+deb9u1
erlang-jiffy 0.14.8+dfsg-1
erlang-lager 3.5.2-1bpo8+1
erlang-mnesia 1:19.2.1+dfsg-2+deb9u1
erlang-odbc 1:19.2.1+dfsg-2+deb9u1
erlang-os-mon 1:19.2.1+dfsg-2+deb9u1
erlang-p1-cache-tab 1.0.10-1bpo8+1
erlang-p1-iconv 1.0.5-1bpo8+1
erlang-p1-mysql 1.0.1-4
erlang-p1-pam 1.0.0-5
erlang-p1-pgsql 1.1.0-4
erlang-p1-sip 1.0.8-2
erlang-p1-stringprep 1.0.9-1bpo8+1
erlang-p1-stun 1.0.7-2
erlang-p1-tls 1.0.15-1bpo8+1
erlang-p1-utils 1.0.9-1bpo8+1
erlang-p1-xml 1.1.23-1bpo8+1
erlang-p1-xmpp 1.1.14-2bpo8+1
erlang-p1-yaml 1.0.10-1bpo8+1
erlang-p1-zlib 1.0.2-1bpo8+1
erlang-proper 1.2+dfsg-1
erlang-public-key 1:19.2.1+dfsg-2+deb9u1
erlang-runtime-tools 1:19.2.1+dfsg-2+deb9u1
erlang-snmp 1:19.2.1+dfsg-2+deb9u1
erlang-ssl 1:19.2.1+dfsg-2+deb9u1
erlang-syntax-tools 1:19.2.1+dfsg-2+deb9u1
erlang-tools 1:19.2.1+dfsg-2+deb9u1
erlang-xmerl 1:19.2.1+dfsg-2+deb9u1
erlang-xmlrpc 0.2014.03.17-2
```
```
ejabberd 17.08-3bpo8+1
ejabberd-contrib 0.2017.10.11dfsg0-1bpo8+1
ejabberd-mod-cron 0.2016.09.12dfsg0-2
ejabberd-mod-log-chat 0.2016.09.12dfsg0-2
ejabberd-mod-logsession 0.2016.09.12dfsg0-2
ejabberd-mod-logxml 0.2016.09.12dfsg0-2
ejabberd-mod-message-log 0.2016.09.12dfsg0-2
ejabberd-mod-muc-log-http 0.2016.09.12dfsg0-2
ejabberd-mod-post-log 0.2016.09.12dfsg0-2
ejabberd-mod-pottymouth 0.2016.09.12dfsg0-2
ejabberd-mod-rest 0.2016.09.12dfsg0-2
ejabberd-mod-s2s-log 0.2016.09.12dfsg0-2
ejabberd-mod-shcommands 0.2016.09.12dfsg0-2
ejabberd-mod-statsdx 0.2016.09.12dfsg0-2
ejabberd-mod-webpresence 0.2016.09.12dfsg0-2
```

**Comment by badlop** [comment]
Your query is correct. Looking at the source code and the error message you got, it seems there are problematic roster items in the database. More concretely, it seems there is some username or servername that, when processed, produces the 'error' string, which is unexpected and the command aborts there.

I don't know if this problem is already solved in recent ejabberd.

In your case, some ideas you can try:
A) if you have the roster table stored in a SQL database, you can perform some SQL query to delete those items. 
B) If you use Mnesia, notice this: if you delete that account, ejabberd will delete its rosteritems, offline messages, and any other information stored for that account. 
C) If you only want to delete its roster, not all the account: you can login to ejabberd WebAdmin, go to the page of that user roster, and delete the problematic roster items.

If all of this fails, comment here and we'll search other solution.

**Comment by Snowmanko** [comment]
Problem is that, I can't recognize which Item is doing this problem. I use mnesia. Can you suggest how to find problematic user/roster item ? Deleting rosters is not a problem, but I have to know what should I delete :)

**Comment by badlop** [comment]
> Can you suggest how to find problematic roster item ? 

It is one of the roster items in the test.user roster. If you look at its roster (using WebAdmin for example, or `ejabberdctl dump`), I guess it will be obvious: some weird characters should appear.

**Comment by Snowmanko** [comment]
I am unable to find such a character. Roster is pretty big and I can't find it manually, I did not found any weird chars. There is over 600 items. Is there another way ? I tried to upgrade to 18.09-2~bpo9+1 but nothing changed so far, problem persists. :(

**Comment by badlop** [comment]
I would say that there's a roster item stored in the mnesia table with username or server = `error`, instead of <<"whatever">>. In fact, I can reproduce your same error report by modifying my mnesia table and setting a roster item where instead of username there's the atom `error`). Then I dump the table to a text file with `ejabberdctl dump /tmp/database.txt`. This is how the problematic roster item looks:
```
{roster,{<<"user1">>,<<"localhost">>,{<<"user3">>,<<"localhost">>,<<>>}},
        {error,<<"localhost">>},
        {<<"user3">>,<<"localhost">>,<<>>},
        <<"user3">>,none,out,[],<<>>,[]}.
```
I think you should have one like this in your database, due to some old problem... and now process_rosteritems is not able to handle it. Take a look, is that your case?

**Comment by cromain** [comment]
I suggest to close this, the dump will show the problematic roster entry which has to be removed from mnesia.
